### ISSUE TITLE
i tried out your tutorial and git cloned your code to compare;

### ISSUE THREAD

**Issue by Tony363** [huiwenhw/django-calendar#7]
from me following your source code, 

> def next_month(d):
    days_in_month = **calendar**.monthrange(d.year, d.month)[1]
    last = d.replace(day=days_in_month)
    next_month = last + timedelta(days=1)
    month = 'month=' + str(next_month.year) + '-' + str(next_month.month)
    return month

calendar is not defined and i don't know where calendar is referenced.

i then tried loading your code from github, and i have 2 issues.

I don't know what to put for new event start time and end time to pass and if i were to click on the calendar button, it would say "no cal_event table" as an error message.

**Comment by devogel55** [comment]
Tony,

 

Thank you for the reply. I did find a solution. 

I realized that the “events” variable was filtered to be events for the current month and year. That was the basic problem. So instead of using “events” as the filtered events to show on the calendar pages,  I used the models variable (RequestPost).

I also constructed a current date variable (date_string) and used that to filter between date_start and date_end. Below is the code that is working the way I want. 

Thank you for putting this out. This is the perfect solution to what I was looking for with my modifications. I would never have been able to do the whole thing myself.

 

Dennis

 

……….

 

  elif day == 30:

      date_now = '-30'

  elif day == 31:

      date_now = '-31'

  else:

       date_now = '-1'      

 

  date_string = str(self.year) + '-' + \

            str(self.month) + date_now

 

    date_object = datetime.strptime(date_string, '%Y-%m-%d')

 

    events_per_day = RequestPost.objects.filter(

          Q(date_start__lte=date_object, date_end__gte=date_object))

 

..................

 

    # formats a month as a table

    # filter events by year and month

    def formatmonth(self, withyear=True):

        events = RequestPost.objects.filter(

            date_start__year=self.year, date_end__month=self.month)

**Comment by Tony363** [comment]
it was a very nice tutorial!

i just did some idling and i figured out the django has an API called calendar. i found out where monthrange is imported from!

thank you you are a great help!
